### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by jw-star** [subinps/VCPlayerBot#109]
```
vc_1  | [01-Jul-22 06:33:26 - ERROR] - utils.logger - Startup was unsuccesfull, Errors - 
vc_1  | Traceback (most recent call last):
vc_1  |   File "/VCPlayerBot/main.py", line 70, in main
vc_1  |     await group_call.start()
vc_1  |   File "/usr/local/lib/python3.9/site-packages/pytgcalls/methods/utilities/start.py", line 38, in start
vc_1  |     await self._start_binding()
vc_1  |   File "/usr/local/lib/python3.9/site-packages/pytgcalls/methods/core/binding_runner.py", line 37, in _start_binding
vc_1  |     await PyTgCallsSession().start()
vc_1  |   File "/usr/local/lib/python3.9/site-packages/pytgcalls/pytgcalls_session.py", line 23, in start
vc_1  |     remote_stable_ver = await self._remote_version('master')
vc_1  |   File "/usr/local/lib/python3.9/site-packages/pytgcalls/pytgcalls_session.py", line 54, in _remote_version
vc_1  |     await get_async(
vc_1  |   File "/usr/local/lib/python3.9/site-packages/pytgcalls/pytgcalls_session.py", line 47, in get_async
vc_1  |     response: ClientResponse = await session.get(url, timeout=5)
vc_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
vc_1  |     break
vc_1  |   File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
vc_1  |     raise asyncio.TimeoutError from None
vc_1  | asyncio.exceptions.TimeoutError
vc_1  | [01-Jul-22 06:33:26 - INFO] - utils.logger - Activating debug mode, you can reconfigure your bot with /env command.

```

**Comment by jw-star** [comment]
```
version: "3"
services:
  vc:
    image: vc
    restart: always
    network_mode: host
    environment:
      API_ID: 1222311
      API_HASH: ffaaaaaaaaaaaaaafff
      BOT_TOKEN: vvvv:AAE5bXffffff4RkyJvvvvvvvvvmvpCEgnbc5IPLrxMCtwODSYk
      SESSION_STRING: BQC4ADrrH-NgGUqQ-7ZeuNKdaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaavvvvvvv
      CHAT: -1001734337606

```
